### ISSUE TITLE
Log in with Chrome

### ISSUE THREAD

**Issue by j-rewerts** [coe-google-apps-support/jazz-chrome#10]
In the event that a user isn't logged in with Chrome, show a simple page that asks them to log into their browser.

**Comment by skaefer143** [comment]
I can add the error checking in, however I don't think it's necessary. To actually install a chrome extension and use it without signing in, you need to do a moderately challenging work around (for the average user): 
https://superuser.com/questions/633706/how-to-install-extensions-in-chrome-without-a-google-account

It should be added in, for error checking, but it isn't the biggest priority I don't think

**Comment by skaefer143** [comment]
Added in [this commit](https://github.com/coe-google-apps-support/jazz-chrome/commit/246bc9a0046a6285108665bae64064d3d9b0e177).
