### ISSUE TITLE
Pre commit hook

### ISSUE THREAD

**Issue by j-rewerts** [coe-google-apps-support/jazz-chrome#12]
When we are committing code, we should have a pre commit hook that checks whether the commit includes license #. If it does, reject the commit.

I'm not too sure if this is possible, but it would be cool.

**Comment by skaefer143** [comment]
Since we have the Config.js code gitignored now, we don't necessarily need this, but could be useful later on.

**Comment by j-rewerts** [comment]
Closing this in favour of using our external config file.
