### ISSUE TITLE
Fix "Response for Preflight" console error

### ISSUE THREAD

**Issue by skaefer143** [coe-google-apps-support/jazz-chrome#13]
When background is working, there is a consistent error showing up in the console. It doesn't affect chat, but I have no idea what this could mean. Will look into it if I have time.

![image](https://user-images.githubusercontent.com/22039892/34126914-6fbe2a82-e3f8-11e7-9810-b777eaa1a072.png)

**Comment by skaefer143** [comment]
Look like it might have something to do with OpenDNS again, somehow

**Comment by skaefer143** [comment]
The livechat disconnecting issue (#3) could possibly be a dependency.

**Comment by skaefer143** [comment]
Happens every 5 minutes, which is odd

**Comment by j-rewerts** [comment]
Since I've closed the issue this references (#3), I'll close this as well .
