### ISSUE TITLE
On my computer, my ip address says I'm from Seattle

### ISSUE THREAD

**Issue by skaefer143** [coe-google-apps-support/jazz-chrome#14]
Probably has to do with the OpenDNS thing. Can possibly be worked around by manually setting the location.

I might not have time to get around to this, but I'm writing it down as an issue.

**Comment by j-rewerts** [comment]
I've heard that the networking team inside the city has changed some of our networking stuff. I wonder if this is causing this.

**Comment by skaefer143** [comment]
That could be it. It seems like there's some redirects happening somewhere through OpenDNS.

**Comment by j-rewerts** [comment]
This is an issue outside the scope of Jazz. The issue doesn't exist on networks outside the City of Edmonton.
