### ISSUE TITLE
Update Repo Description

### ISSUE THREAD

**Issue by skaefer143** [coe-google-apps-support/jazz-chrome#23]
Hey! If you have a minute, could you upgrade the repo description to this?

"Jazz is an application wrapper for LiveChat's JS API widget, used as a support application for City of Edmonton internal executive employees. It is in development for iOS, Android, and Chrome as an extension."

Or something along the lines of that.

Also, while you're at it, feel free to take me off the coe-google-apps-support organization. I promise I won't do bad things, but just as a precaution ;) 

Thanks Jared!

**Comment by j-rewerts** [comment]
Done.
