### ISSUE TITLE
Get Chrome device settings, put into livechat variables

### ISSUE THREAD

**Issue by skaefer143** [coe-google-apps-support/jazz-chrome#5]
This depends if we're using the [Livechat visitor SDK](https://docs.livechatinc.com/visitor-sdk) or not. 

If we are, we'd have to use the `customProperties` in this example code:
````javascript
visitorSDK.setVisitorData({
    name: "Wynton Marsalis",
    email: "test@livechatinc.com",
    pageUrl: 'http://example.org/pricing',
    pageTitle: 'Pricing',
    customProperties: {
        login: 'wyntonmarsalis',
        customerId: '18260556127834'
    }
})
````

**Comment by skaefer143** [comment]
Actually, just realized this is shown when chatting from our extension popup already. Is this good enough @j-rewerts?

![image](https://user-images.githubusercontent.com/22039892/33505592-325d023c-d6a9-11e7-8c9b-d571fd7cda7a.png)

**Comment by j-rewerts** [comment]
Feel free to put this on the back burner for now. In the future, I'll probably want it all formatted the same across all platforms (Device: and OS:).

**Comment by j-rewerts** [comment]
Just a heads up, you can use custom properties with the JS API [like so](https://docs.livechatinc.com/js-api/#set-custom-variables). Not too sure how to do it if we are just loading the pop up url one though.

**Comment by j-rewerts** [comment]
Closing this issue. The navigator.userAgent approach will have to do for now.
