### ISSUE TITLE
Multiple dings are annoying

### ISSUE THREAD

**Issue by j-rewerts** [coe-google-apps-support/jazz-chrome#8]
Dana mentioned that the first ding is useful, as it can notify you about the chat. After that, we should set some timeout on it.

**Comment by skaefer143** [comment]
Do you mean the red text that counts up for every new message (when the popup works properly)? Okay, yeah that's pretty easy to change.

**Comment by j-rewerts** [comment]
Nope. The actual audible sound.

**Comment by skaefer143** [comment]
Ah, I never actually noticed that. Ok I'll look into it

**Comment by skaefer143** [comment]
@j-rewerts Since livechat has no way to turn sounds on again, will disabling sounds after the first received message in the chat work? Just so there's at least one sound. 

I can also disable sounds all together. Your call.

**Comment by j-rewerts** [comment]
I think we should leave it disabled for now. Lets leave this issue open though.

**Comment by skaefer143** [comment]
Sounds are disabled in background.
